hub:
  built-in-frontend: "on"
  frontend: "http://localhost:80/"
  workspace: "./"

server:
  port: 3000

logging:
  level:
    org:
      springframework: WARN
      apache: WARN
      jline: ERROR
      panda_lang: WARN
      mongodb: WARN
    springfox: WARN

springfox:
  documentation:
    swagger:
      v2:
        path: "/api/docs"

spring:
  main:
    banner-mode: "off"
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${oauth.client.id}
            clientSecret: ${oauth.client.secret}
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user